# Cloud build to demonstrate timeout issue
#
steps:
  #
  # Setup - Here we need to configure things for 'docker buildx' to work.
  #
  - id: setup
    name: ${_CLOUDBUILD_IMAGE}
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # configure binfmt_misc with other architectures (e.g., arm64)
        # this also, weirdly, seems to also make 'buildx' a recognized
        # docker command (running 'docker buildx version' prior to this
        # results in "'buildx' is not a docker command." error)
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker version
        docker buildx version
        echo "Ready, set, build!"
  #
  # Buildx that takes a while
  #
  - id: long-build
    name: ${_CLOUDBUILD_IMAGE}
    entrypoint: "sh"
    args:
      - "-c"
      - |
        set -o errexit
        REPO=${_REPO} make ${_TARGET}
substitutions:
  _REPO: doug-test
  # Where to find cloud builder image (set via Makefile)
  _CLOUDBUILD_IMAGE: us-central1-docker.pkg.dev/GCP_PROJECT/REPO/build/cloud-build:alpine3.15
  # make target
  _TARGET: no-target-provided
options:
  machineType: "E2_HIGHCPU_8"
tags: ["build-timeout"]
# Build timeout is 2 hours, which shows that *this* timeout is not causing the failure
timeout: 7200s
